name: abrar
description: "Best Online Shop"

publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  iconsax: ^0.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/


  fonts:
    - family: Telenor
      fonts:
        - asset: assets/fonts/Telenor-Light.ttf
          weight: 300
        - asset: assets/fonts/Telenor-Medium.ttf
          weight: 500
        - asset: assets/fonts/Telenor-Bold.ttf
          weight: 800
    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri-Regular.ttf



  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
